// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                int64
	OwnerID           int64
	CurrencyID        int64
	AccounttypeID     int64
	Accountname       string
	Openingbalance    pgtype.Numeric
	Openingdate       pgtype.Date
	Balance           pgtype.Numeric
	Institution       pgtype.Text
	Accountnumber     pgtype.Text
	AccountcategoryID pgtype.Int8
	Notes             pgtype.Text
}

type AccountCategory struct {
	ID              int64
	AccountCategory string
}

type AccountType struct {
	ID          int64
	Accounttype string
}

type Currency struct {
	ID       int64
	Currency string
}

type Owner struct {
	ID           int64
	Ownername    string
	Emailaddress string
	Birthdate    pgtype.Date
}

type Transaction struct {
	ID                    int64
	FromaccountID         int64
	ToaccountID           int64
	TransactiontypeID     int64
	Transdate             pgtype.Date
	Amount                pgtype.Numeric
	TransactioncategoryID pgtype.Int8
	Notes                 pgtype.Text
}

type TransactionCategory struct {
	ID                  int64
	Transactioncategory string
}

type TransactionType struct {
	ID              int64
	Transactiontype string
}
